server:
  port: 8080
spring:
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/multbooks?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&useSSL=false
    username: multbooks
    password: multbooks
  jpa:
    hibernate:
      ddl-auto: create