spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MariaDB53Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
