spring :
  mail :
    host : smtp.gmail.com
    port : 587
    username : shzero211@gmail.com
    password : gaxscykuxbgnwxty
    properties :
      mail :
        smtp :
          auth : true
          starttls :
            enable : true